- crowdin/src/main/java/com/crowdin/platform/data/remote/BaseRepository.kt
ADD support export pattern language, two_letter_code, three_letters_code
> ADD support export pattern language, two_letter_code, three_letters_code

- crowdin/src/main/java/com/crowdin/platform/data/remote/BaseRepository.kt
> Fix default path to dir

- crowdin/build.gradle
> Fix exist Java Kotlin Plugin

- README.md
> WIP: New Badges: build, codecov, tests

- build.gradle
- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
- crowdin/src/main/java/com/crowdin/platform/CrowdinConfig.kt
- crowdin/src/main/java/com/crowdin/platform/auth/AuthActivity.kt
- crowdin/src/main/java/com/crowdin/platform/data/model/ManifestData.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/MappingRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/StringDataRemoteRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/api/CrowdinDistributionApi.kt
- crowdin/src/test/java/com/crowdin/platform/CrowdinConfigTest.kt
- crowdin/src/test/java/com/crowdin/platform/LocalStringRepositoryFactoryTest.kt
- crowdin/src/test/java/com/crowdin/platform/MappingRepositoryTest.kt
- crowdin/src/test/java/com/crowdin/platform/RecurringManagerTest.kt
- crowdin/src/test/java/com/crowdin/platform/SessionInterceptorTest.kt
- crowdin/src/test/java/com/crowdin/platform/StringDataRemoteRepositoryTest.kt
- crowdin/src/test/java/com/crowdin/platform/ViewTransformerManagerTest.kt
- example/src/main/java/com/crowdin/platform/example/App.kt
[Description]
- remove filePath from config file;
- automatically download files depending on project release;
- upgrade gradle versions;
> Download manifest file, internally;

- README.md
- Drop `withFilePaths` config option from readme
> Drop 'withFilePaths' config option from the Readme

- build.gradle
- crowdin/build.gradle
- crowdin/src/main/java/com/crowdin/platform/CrowdinResources.kt
- crowdin/src/main/java/com/crowdin/platform/ShakeDetectorManager.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/CrowdinRetrofitService.kt
- crowdin/src/main/java/com/crowdin/platform/recurringwork/RecurringManager.kt
- example/build.gradle
- update gradle plugin version;
- set kotlin jvm to 1.8;
- update appcompat, work-runtime-ktx, retrofit, kotlin-stdlib-jdk8 versions;
- update deprecated methods;
> Libraries update;

- build.gradle
- crowdin/build.gradle
- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/api/CrowdinApi.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/api/CrowdinNetworkModels.kt
- crowdin/src/main/java/com/crowdin/platform/screenshot/ScreenshotManager.kt
- crowdin/src/main/java/com/crowdin/platform/util/Extensions.kt
- crowdin/src/test/java/com/crowdin/platform/ScreenshotManagerTest.kt
- example/src/main/java/com/crowdin/platform/example/App.kt
- update storage API and models;
- add new localized format for screenshots names with activity tag;
- update gradle and kotlin tools;
> API update and minor improvements;

- crowdin/build.gradle
- crowdin/src/main/java/com/crowdin/platform/data/remote/CrowdinRetrofitService.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/interceptor/HeaderInterceptor.kt
- add user agent header to all API requests;
> Add User-agent header;

- crowdin/src/main/java/com/crowdin/platform/data/DataManager.kt
- crowdin/src/test/java/com/crowdin/platform/DataManagerTest.kt
- add suffix to mapping when store data;
> App shows mapping IDs instead of source language;

- README.md
- crowdin/src/main/java/com/crowdin/platform/CrowdinConfig.kt
- example/src/main/java/com/crowdin/platform/example/App.kt
- update interval time to seconds;
> Config update;

- build.gradle
- crowdin/build.gradle
- crowdin/src/main/AndroidManifest.xml
- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
- crowdin/src/main/java/com/crowdin/platform/CrowdinResources.kt
- crowdin/src/main/java/com/crowdin/platform/auth/AuthActivity.kt
- crowdin/src/main/java/com/crowdin/platform/data/DataManager.kt
- crowdin/src/main/java/com/crowdin/platform/data/local/MemoryLocalRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/model/LanguageData.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/StringDataRemoteRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/TranslationDataRepository.kt
- crowdin/src/main/java/com/crowdin/platform/util/Extensions.kt
- crowdin/src/main/java/com/crowdin/platform/util/ResourceConverter.kt
- crowdin/src/main/java/com/crowdin/platform/util/UiUtil.kt
- crowdin/src/main/res/layout/auth_layout.xml
- crowdin/src/main/res/values/strings.xml
- crowdin/src/main/res/values/styles.xml
- crowdin/src/test/java/com/crowdin/platform/MemoryLocalRepositoryTest.kt
- example/build.gradle
- new auth flow inside app instead of redirect to browser;
- update to naming inside locale storage;
- new public methods for retrieving string and json by locale code;
- update library versions kotlin/gradle etc;
> Authorization flow update;

- README.md
Based on my research in https://github.com/crowdin/mobile-sdk-android/issues/54
I've optimized the solution when GSON conflicts.
> Optimize solution for GSON conflicts.

- README.md
Change numeric order to list dot, to avoid people think that the Installation have two steps. (but its actually have two options)
> Update words to clear Installation guide

- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
- load mapping as a last SDK initialization step;
> Bug: mapping not loaded when interval updates enabled;

- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
- crowdin/src/main/java/com/crowdin/platform/data/parser/JsonReader.kt
- crowdin/src/main/java/com/crowdin/platform/data/parser/Reader.kt
- crowdin/src/main/java/com/crowdin/platform/data/parser/ReaderFactory.kt
- crowdin/src/main/java/com/crowdin/platform/data/parser/XmlReader.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/MappingRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/StringDataRemoteRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/TranslationDataRepository.kt
- crowdin/src/test/java/com/crowdin/platform/MappingRepositoryTest.kt
- crowdin/src/test/java/com/crowdin/platform/StringDataRemoteRepositoryTest.kt
- crowdin/src/test/java/com/crowdin/platform/StubResponseBody.kt
- crowdin/src/test/java/com/crowdin/platform/TranslationDataRepositoryTest.kt
- crowdin/src/test/java/com/crowdin/platform/XmlReaderTest.kt
- add parser for xml/json files in distribution;
> JSON support;

- build.gradle
- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
- crowdin/src/main/java/com/crowdin/platform/ResourcesCallback.kt
- crowdin/src/main/java/com/crowdin/platform/data/DataManager.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/MappingRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/RemoteRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/StringDataRemoteRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/TranslationDataRepository.kt
- add new get resources by locale method for async. data downloading by specified language code;
- gradle update;
> Support resource downloading by language code;

- crowdin/src/main/java/com/crowdin/platform/data/parser/StringResourceParser.kt
Replace only backslash with quotes
> Add hot fix

- crowdin/src/main/java/com/crowdin/platform/data/local/MemoryLocalRepository.kt
- catch IllegalFormatException which is parent of IllegalFormatConversionException and UnknownFormatConversionException;
Closes #83
> [#108] - UnknownFormatConversionException;

- crowdin/src/main/java/com/crowdin/platform/data/model/FileResponse.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/TranslationDataRepository.kt
- crowdin/src/test/java/com/crowdin/platform/TranslationDataRepositoryTest.kt
- add path to fileData model;
- compare file paths to download files from distribution only;
- reduce API calls by changing for-loop structure;
> [#117] - RealTime updates download all files from project by name;

- crowdin/src/main/java/com/crowdin/platform/data/Mapping.kt
- crowdin/src/main/java/com/crowdin/platform/data/model/TextMetaData.kt
- crowdin/src/main/java/com/crowdin/platform/realtimeupdate/EchoWebSocketListener.kt
- crowdin/src/main/java/com/crowdin/platform/screenshot/ScreenshotManager.kt
- crowdin/src/test/java/com/crowdin/platform/MappingTest.kt
- check hint attribute and subscribe view for updates;
- update unit tests;
> [#114] - Hint attributes not handled/updated when RealTime-updates ON;

- crowdin/src/main/java/com/crowdin/platform/CrowdinResources.kt
- crowdin/src/main/java/com/crowdin/platform/data/parser/StringResourceParser.kt
- crowdin/src/main/java/com/crowdin/platform/realtimeupdate/EchoWebSocketListener.kt
- crowdin/src/main/java/com/crowdin/platform/util/Extensions.kt
> [#118] Handle `new lines` inside of string resources;

- example/src/main/java/com/crowdin/platform/example/BaseActivity.kt
- example/src/main/java/com/crowdin/platform/example/MainActivity.kt
- init controls on each activity. In this case screenshot receiver will work with active activity;
> [#115] Screenshot captures only root activity;

- README.md
- build.gradle
- crowdin-controls/build.gradle
- crowdin-controls/install.gradle
- crowdin-controls/maven.gradle
- crowdin/build.gradle
- crowdin/maven.gradle
- example/src/main/java/com/crowdin/platform/example/MainActivity.kt
- bump version;
- set up publishing of controls module;
- remove bintray part;
> Jitpack migration;

- ci/basic.yml
- crowdin-controls/build.gradle
- crowdin/src/main/java/com/crowdin/platform/screenshot/ScreenshotService.kt
- example/build.gradle
- example/src/main/java/com/crowdin/platform/example/App.kt
- example/src/main/java/com/crowdin/platform/example/category/DBManagerCategory.kt
- example/src/main/java/com/crowdin/platform/example/task/DBManagerTask.kt
[Description]
- fix CI errors and update config
> Lint updates

- example/src/main/java/com/crowdin/platform/example/App.kt
**[RC]**
SourceLanguage marked as optional part of config. But need to be checked
**[Fix]**
Updated examples of config parts and markers
> Edited App init part with more details

- build.gradle
- crowdin-controls/build.gradle
- crowdin/build.gradle
- example-info/build.gradle
**[Fix]**
Using variable for all modules
Using Version 30
> Unified compile sdk version

- example/src/main/java/com/crowdin/platform/example/BaseActivity.kt
- example/src/main/java/com/crowdin/platform/example/utils/CommonUtils.kt
- example/src/main/res/values-uk/strings.xml
- fix issue with bundle resource not used when change locale programmatically;
- add new string resources;
> Use default string resources when change locale programmatically; 

- crowdin/src/main/java/com/crowdin/platform/CrowdinConfig.kt
- crowdin/src/test/java/com/crowdin/platform/CrowdinConfigTest.kt
**[RC]**
Currently min refresh interval is 15 min but user can set value below
**[Fix]**
If user set value lower 15 min he will receive exception while app starts
> Added checking for refresh interval

- crowdin-controls/build.gradle
- crowdin-controls/src/main/java/com/crowdin/crowdin_controls/CrowdinWidgetService.kt
- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
**[RC]**
Without internet when we click button log in, user see empty page inside webview
**[Fix]**
Shows toast with missing Internet connection
> Showing error while login without internet connection

- README.md
- build.gradle
- crowdin-controls/build.gradle
- crowdin-controls/maven.gradle
- crowdin/build.gradle
- crowdin/maven.gradle
- crowdin/src/main/java/com/crowdin/platform/auth/AuthActivity.kt
- crowdin/src/main/java/com/crowdin/platform/data/model/AuthInfo.kt
- crowdin/src/main/res/layout/auth_layout.xml
- example-info/build.gradle
- example/build.gradle
- example/src/main/java/com/crowdin/platform/example/MainActivity.kt
- example/src/main/java/com/crowdin/platform/example/SettingsFragment.kt
- example/src/main/java/com/crowdin/platform/example/category/CategoryAdapter.kt
- example/src/main/java/com/crowdin/platform/example/category/CategoryFragment.kt
- example/src/main/java/com/crowdin/platform/example/task/AddTaskActivity.kt
- example/src/main/java/com/crowdin/platform/example/task/TaskAdapter.kt
- example/src/main/java/com/crowdin/platform/example/task/fragment/DashboardFragment.kt
- example/src/main/java/com/crowdin/platform/example/task/fragment/HistoryFragment.kt
- example/src/main/res/layout/activity_add_task.xml
- example/src/main/res/layout/activity_splash.xml
- example/src/main/res/values/colors.xml
- gradle/wrapper/gradle-wrapper.properties
[Description]
- remove deprecated kotlin-android-extensions;
- update: gradle / gradle-wrapper / junit / workmanager/ material / converter-gson / gson / logging-interceptor / kotlin-std
- code cleanup;
> Library version updates

- crowdin-controls/src/main/java/com/crowdin/crowdin_controls/CrowdinWidgetService.kt
- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
**[RC]**
Currently if feature CaptureScreenshot is disabled button works not in proper way
**[Fix]**
Disable button "capture sreenshot" on widget if feature is not enabled
> Disable button "capture sreenshot" on widget if feature is not enabled

- crowdin-controls/build.gradle
- crowdin-controls/src/main/java/com/crowdin/crowdin_controls/CrowdinWidgetService.kt
- crowdin/build.gradle
- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
- crowdin/src/main/java/com/crowdin/platform/auth/AuthActivity.kt
- crowdin/src/main/java/com/crowdin/platform/screenshot/ScreenshotManager.kt
- crowdin/src/main/java/com/crowdin/platform/screenshot/ScreenshotService.kt
- crowdin/src/main/res/values/strings.xml
- settings.gradle
**[RC]**
Currently we shows permission access dialog immediately after log in.
Need runtime permission request
**[Fix]**
- Removed permission dialog after log in
- Added dialog showing after Screenshot made and in case when permission is missing
- Showing error if this permission is not granted by user
> Runtime permissions for screenshot uploading

- crowdin-controls/src/main/java/com/crowdin/crowdin_controls/CrowdinWidgetService.kt
**[RC]**
During refactoring reference to capture screen button was deleted. As result crash on startup
**[Fix]**
Fixed code
> fixed problem with null reference to capture screen button

- crowdin-controls/src/main/java/com/crowdin/crowdin_controls/CrowdinWidgetService.kt
- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
- crowdin/src/main/java/com/crowdin/platform/auth/AuthActivity.kt
- crowdin/src/main/java/com/crowdin/platform/realtimeupdate/RealTimeUpdateManager.kt
Automatically after auth
Automatically after start application
> Automatically start realtime preview if present in config

- README.md
- crowdin-controls/build.gradle
- crowdin-controls/src/main/java/com/crowdin/crowdin_controls/CrowdinWidgetService.kt
- crowdin/build.gradle
- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
- crowdin/src/main/java/com/crowdin/platform/auth/AuthActivity.kt
- crowdin/src/main/java/com/crowdin/platform/data/DataManager.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/StringDataRemoteRepository.kt
- crowdin/src/main/java/com/crowdin/platform/realtimeupdate/RealTimeUpdateManager.kt
- crowdin/src/main/java/com/crowdin/platform/screenshot/ScreenshotManager.kt
- crowdin/src/main/java/com/crowdin/platform/screenshot/ScreenshotService.kt
- crowdin/src/main/res/values/strings.xml
- example/src/main/java/com/crowdin/platform/example/SplashScreenActivity.kt
- example/src/main/res/layout/activity_splash.xml
- settings.gradle
**[RC]**
Currently we have situation of starting application without waiting translation
**[Fix]**
Added callbacks for loading translations.
Added example of using callbacks into SplashScreenActivity
> Added callbacks for loading translations

- README.md
- crowdin/build.gradle
**[CHANGELOG]**
- Added callbacks for loading translations (#127)
- Automatically start Real-Time Preview if present in config (#128)
- Runtime permissions for screenshot uploading (#125)
- Disable button "capture screenshot" on widget if feature is not enabled (#129)
- Fixed problem with null reference to capture screen button (#131)
- Fixed problem "permission denied for window type 2038" (#137)
> Version 1.4.3

- crowdin-controls/src/main/java/com/crowdin/crowdin_controls/CrowdinWidgetService.kt
- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
- crowdin/src/main/java/com/crowdin/platform/data/DataManager.kt
- crowdin/src/main/java/com/crowdin/platform/data/model/ManifestData.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/BaseRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/CrowdingRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/MappingRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/StringDataRemoteRepository.kt
- crowdin/src/main/java/com/crowdin/platform/data/remote/TranslationDataRepository.kt
- crowdin/src/test/java/com/crowdin/platform/MappingRepositoryTest.kt
- crowdin/src/test/java/com/crowdin/platform/TestCommon.kt
**[RC]**
Implementation of language mapping feature
**[Fix]**
Now when we have placeholder in language mapping settings (two_letters_code etc) it will be automatically changed by custom code
> Language mapping feature

- README.md
- crowdin/build.gradle
- Language mapping support (#132)
- Fix bug with context wrapping (#140)
> Version 1.4.4

- README.md
- crowdin/src/main/java/com/crowdin/platform/CrowdinContextWrapper.kt
- crowdin/src/main/java/com/crowdin/platform/CrowdinLayoutInflater.kt
- fix context theme overriding;
- fix issue with creation of custom views. Now we have list of supported components and we skip creation of view if view name not in the list;
> Context wrap with custom views and context theme overriding

- README.md
Feature/lib updates (#144)
Context wrap with custom views and context theme overriding (#143)
> Version 1.4.5

- README.md
- crowdin/build.gradle
- Custom languages support (#158)
- Using compile and target version 31 (#157)
> Version 1.5.0

- crowdin/src/main/java/com/crowdin/platform/data/remote/interceptor/SessionInterceptor.kt
Fixed crash-while-implementing-real-time-updates
> close response before chain proceed

- README.md
- crowdin/build.gradle
- Rewritten deprecated code (#162)
- Close response before chain proceed (#161)
> Version 1.5.1

- README.md
- crowdin/build.gradle
- Modifies maps with text view's as keys to use weak hash maps #169
> Version 1.5.2

- README.md
- crowdin/build.gradle
- Fix updateResources method to update all resource types (#172)
> Version 1.5.3

- README.md
- crowdin/build.gradle
- Fix duplicated API calls during synchronized mode (#174)
> Version 1.5.4

- README.md
- crowdin/build.gradle
- Add mapping for Hebrew language code he/iw in #176 by @MykhailoNester
> Version 1.5.5

- crowdin/src/main/java/com/crowdin/platform/data/remote/StringDataRemoteRepository.kt
fixes https://github.com/crowdin/mobile-sdk-android/issues/188
> Fixes an issue where a NPE is thrown when the preferred language is changed

- crowdin/src/main/java/com/crowdin/platform/Crowdin.kt
Fixes https://github.com/crowdin/mobile-sdk-android/issues/185
> Now safely wraps context without crashing

- build.gradle
- crowdin/build.gradle
- crowdin/src/main/java/com/crowdin/platform/screenshot/ScreenshotService.kt
- crowdin/src/main/res/values/strings.xml
- example/src/main/AndroidManifest.xml
- website/docs/installation.md
- Increment sdk to 33. 
- Add new READ_MEDIA_IMAGES permission in example project manifest and additional check in ScreenshotService.kt ;
#193
> Support automatic screenshot loading on android 13 

- crowdin/src/main/java/androidx/appcompat/app/BaseContextWrappingDelegate.kt
> Add delegate methods to support new pre-app language preferences;

- build.gradle
- crowdin/src/main/java/com/crowdin/platform/CrowdinLayoutInflater.kt
- example-info/build.gradle
- example/build.gradle
- update min sdk version;
- use createView with context parameter;
Fixed #206
> Use context during view creation

- build.gradle
- crowdin/src/main/java/com/crowdin/platform/CrowdinLayoutInflater.kt
- example-info/build.gradle
- example/build.gradle
Reverts crowdin/mobile-sdk-android#207
> Revert "Use context during view creation"
